export const ONLINE_USERS_ACTIONS = {
	UPDATE_ONLINE: "UPDATE_ONLINE",
	FETCH_SELECTED_USER_LOADING: "FETCH_SELECTED_USER_LOADING",
	FETCH_SELECTED_USER_SUCCESS: "FETCH_SELECTED_USER_SUCCESS",
};

export const ROOM_LIST_ACTION = {
	GET_ROOMS_SUCCESS: "GET_ROOMS_SUCCESS",
	GET_ROOMS_LOADING: "GET_ROOMS_LOADING",
	SELECT_ROOM: "SELECT_ROOM",
	UPDATE_ROOM_LIST: "UPDATE_ROOM_LIST",
};

export const GAME_ACTIONS = {
	CLICK: "CLICK",
	REFRESH_GAME: "REFRESH_GAME",
	SAVE_GAME: "SAVE_GAME",
	REQUEST: "REQUEST",
	CHAT: "CHAT",
	SET_SURRENDER: "SET_SURRENDER",
	SET_DRAW: "SET_DRAW",
	SET_WINNER: "SET_WINNER",
};

export const ROOM_ACTIONS = {
	// old
	JOIN_ROOM: "JOIN_ROOM",
	REFRESH: "REFRESH",
	CHAT_ROOM: "CHAT_ROOM",

	// new
	JOIN_ROOM_SUCCESS: "JOIN_ROOM_SUCCESS",
	LEAVE_ROOM: "LEAVE_ROOM",
	RECEIVE_CHAT: "RECEIVE_CHAT",

	SET_IS_JOIN_GAME: "SET_IS_JOIN_GAME",
	SET_TIME: "SET_TIME",
};

export const PROFILE_ACTIONS = {
	GET_USER_INFO: "GET_USER_INFO",
};
